source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.1'

gem 'bootsnap', '>= 1.4.2', require: false
gem 'jbuilder', '~> 2.7'
gem 'pagy', '~> 3.8'
gem 'puma', '~> 4.3'
gem 'rack-cors'
gem 'rails', '~> 6.0.3'

group :production, :development do
  gem 'pg', '~> 1.2'
end

group :development, :test do
  gem 'awesome_print', '~> 1.8'
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails', '~> 5.2'
  gem 'ffaker', '~> 2.14'
end

group :test do
  gem 'database_cleaner', '~> 1.8'
  gem 'rspec-rails', '~> 4.0'
end

group :development do
  gem 'listen', '~> 3.2'
  gem 'rubocop', '~> 0.82.0'
  gem 'rubocop-rspec', '~> 1.39'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
