source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.1'

gem 'bootsnap', '>= 1.4.2', require: false
gem 'jbuilder', '~> 2.7'
gem 'rack-cors'
gem 'rails', '~> 6.0.3'
gem 'puma', '~> 4.1'
# gem 'redis', '~> 4.0'

group :production, :development do
  gem 'pg', "~> 1.2"
end

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'listen', '~> 3.2'
  gem 'rubocop', "~> 0.82.0"
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end




